// Comic mode (experimental, OPENOVEL_ENABLE_COMIC_MODE): pure helpers for the
// panel-script channel, shared by the runtime (path injection, canon
// derivation, panel image generation) and the renderer (ComicStrip display).
// Keep this module dependency-light and DOM/node-free (renderer-safe, like
// ovlFences.js / includePaths.js).
//
// In comic mode the foreground model emits, instead of prose, a PANEL SCRIPT:
// a sequence of reserved ```ovl:panel``` fences (fields: prompt / caption, one
// field per line with continuation lines folding into the open field) followed
// by ONE reserved ```ovl:synopsis``` fence (a compact text record of the turn).
//
// Division of labor (mirrors the dual-loop philosophy):
//   - The MODEL writes prompts + captions + synopsis. It never picks file
//     paths: the runtime injects a deterministic `image:` line per panel
//     (story/includes/comic/<turnId>/p<N>.png) at finalize time, so replayed
//     transcripts and scene_log carry the full mapping in the text itself.
//   - chapters.md (text canon for the slow loop + exports) gets the DERIVED
//     prose (captions + synopsis), never the raw fences/prompts.
//   - Panel bytes are generated by the runtime (runtime/comicPanels.js) and
//     served through the existing ovl-asset:// trust boundary.

import { normalizeOvlFences } from "./ovlFences.js"
import { isUnsafeIncludePath, isUnderIncludes, classifyInclude } from "./includePaths.js"

// All panel images live under this prefix. The runtime refuses to generate
// outside it so a drifted script can never overwrite other includes media
// (cover.*, beats/, bg/, characters/).
export const COMIC_IMAGE_PREFIX = "story/includes/comic/"

const CLOSED_PANEL_RE = /```ovl:panel[^\n]*\n([\s\S]*?)```/gi
const CLOSED_SYNOPSIS_RE = /```ovl:synopsis[^\n]*\n([\s\S]*?)```/gi
// A trailing, still-streaming fence: an opener whose body never closes. Only
// honored when the captured body contains no further fence marker (otherwise
// it would swallow later fences of another kind).
const TRAILING_PANEL_RE = /```ovl:panel[^\n]*\n([\s\S]*)$/i
const TRAILING_SYNOPSIS_RE = /```ovl:synopsis[^\n]*\n([\s\S]*)$/i

const PANEL_FIELDS = new Set(["image", "prompt", "caption", "characters"])

// ASCII ":" or fullwidth "：" (a CJK model naturally types the latter); both
// are single UTF-16 units so slice(idx + 1) stays correct.
function firstColon(seg) {
  const a = seg.indexOf(":")
  const b = seg.indexOf("：")
  if (a < 0) return b
  if (b < 0) return a
  return Math.min(a, b)
}

// Parse one panel fence body. Field lines open a field (image: / prompt: /
// caption: / characters:); any other line continues the currently-open field,
// so prompts and captions may run multiple lines. Unknown keys are treated as
// continuation text (a colon inside a caption sentence must not eat the
// line). Total over partial input; never throws.
function parsePanelBody(body) {
  const fields = { image: "", prompt: "", caption: "", characters: "" }
  let open = null
  for (const line of String(body ?? "").split(/\r?\n/)) {
    const seg = line.trim()
    if (!seg) { if (open) fields[open] += "\n"; continue }
    const colon = firstColon(seg)
    const key = colon > 0 ? seg.slice(0, colon).trim().toLowerCase() : ""
    if (PANEL_FIELDS.has(key)) {
      open = key
      const value = seg.slice(colon + 1).trim()
      fields[key] = fields[key] ? `${fields[key]}\n${value}` : value
    } else if (open) {
      fields[open] = fields[open] ? `${fields[open]}\n${seg}` : seg
    }
  }
  return {
    image: fields.image.split(/\s/)[0] || "",
    prompt: fields.prompt.replace(/\n+/g, "\n").trim(),
    caption: fields.caption.replace(/\n{2,}/g, "\n").trim(),
    // Who is visibly IN FRAME (recurring characters only) — the runtime keys
    // reference-sheet selection off this list, so scenery panels carry none.
    characters: fields.characters
      .split(/[、,，;；/\n]+/)
      .map((name) => name.trim())
      .filter(Boolean),
  }
}

// Validate a panel's (runtime-injected) image path against the include trust
// rules PLUS the comic prefix. Returns "" reason when ok.
export function panelImagePathIssue(rel) {
  const value = String(rel || "")
  if (!value) return "no image path"
  if (isUnsafeIncludePath(value) || !isUnderIncludes(value)) return "path must be inside story/includes/ (no .., no absolute path)"
  if (!value.startsWith(COMIC_IMAGE_PREFIX)) return `panel images live under ${COMIC_IMAGE_PREFIX}`
  if (classifyInclude(value) !== "image") return "panel image must use an image extension"
  // classifyInclude treats svg as a displayable image (user-supplied includes
  // may be svg), but panels are GENERATED bytes and the write gate refuses
  // svg; reject it up front so the pipeline never aims at an unwritable path.
  if (/\.svg$/i.test(value)) return "svg panels are not supported"
  return ""
}

// Parse a (possibly partial) narration text into the comic panel model.
// Returns { panels, synopsis, isComic }:
//   panel: { index, image, imageIssue, prompt, caption, open }
//     image      runtime-injected rel path ("" while streaming / pre-inject)
//     imageIssue "" when the path is renderable/generatable, else the reason
//     open       true for the trailing still-streaming fence
//   synopsis: text of the LAST closed (or trailing open) synopsis fence, "".
//   isComic: at least one panel fence (open or closed) is present.
// Total over partial input; never throws.
export function parsePanelScript(text) {
  const s = normalizeOvlFences(String(text ?? "")).text
  const panels = []
  let m
  CLOSED_PANEL_RE.lastIndex = 0
  while ((m = CLOSED_PANEL_RE.exec(s))) {
    const parsed = parsePanelBody(m[1])
    panels.push({ index: panels.length, ...parsed, imageIssue: panelImagePathIssue(parsed.image), open: false })
  }
  // Trailing open panel fence (mid-stream): text after the last closed fence
  // of ANY kind that opens a panel and never closes it.
  const afterClosed = s.slice(lastClosedFenceEnd(s))
  const tail = TRAILING_PANEL_RE.exec(afterClosed)
  if (tail && !tail[1].includes("```")) {
    const parsed = parsePanelBody(tail[1])
    panels.push({ index: panels.length, ...parsed, imageIssue: panelImagePathIssue(parsed.image), open: true })
  }
  let synopsis = ""
  CLOSED_SYNOPSIS_RE.lastIndex = 0
  while ((m = CLOSED_SYNOPSIS_RE.exec(s))) synopsis = m[1].trim()
  if (!synopsis) {
    const openSyn = TRAILING_SYNOPSIS_RE.exec(afterClosed)
    if (openSyn && !openSyn[1].includes("```")) synopsis = openSyn[1].trim()
  }
  return { panels, synopsis, isComic: panels.length > 0 }
}

function lastClosedFenceEnd(s) {
  const re = /```ovl:[a-z0-9-]+[^\n]*\n[\s\S]*?```/gi
  let end = 0
  let m
  while ((m = re.exec(s))) end = m.index + m[0].length
  return end
}

// Deterministic per-panel image path. turnId comes from the session processor
// (e.g. "turn_012"); panel numbering is 1-based for human-readable filenames.
// `ext` follows the provider's actual output format (expectedImageKind in
// provider/imageGeneration.js): naming the file before generating means the
// extension must match the bytes that will arrive, or the byte-sniff gate
// rejects the save.
export function comicPanelRelPath(turnId, index, ext = "png") {
  const slug = String(turnId || "turn").replace(/[^a-zA-Z0-9_-]+/g, "-")
  const safeExt = String(ext || "png").toLowerCase().replace(/^jpeg$/, "jpg")
  return `${COMIC_IMAGE_PREFIX}${slug}/p${index + 1}.${safeExt}`
}

// Inject runtime-assigned `image:` lines into each panel fence of a COMPLETE
// script (idempotent: an existing image line is replaced, not duplicated).
// Returns the rewritten text; non-panel content is untouched.
export function injectPanelImagePaths(text, turnId, { ext = "png" } = {}) {
  const s = normalizeOvlFences(String(text ?? "")).text
  let index = 0
  return s.replace(CLOSED_PANEL_RE, (whole, body) => {
    const rel = comicPanelRelPath(turnId, index, ext)
    index += 1
    const kept = String(body)
      .split(/\r?\n/)
      .filter((line) => {
        const seg = line.trim()
        const colon = firstColon(seg)
        const key = colon > 0 ? seg.slice(0, colon).trim().toLowerCase() : ""
        return key !== "image"
      })
      .join("\n")
      .replace(/^\n+/, "")
      .replace(/\n+$/, "")
    return "```ovl:panel\n" + `image: ${rel}\n` + kept + "\n```"
  })
}

// Derive the TEXT canon for a comic turn: captions in story order, then the
// synopsis as a closing paragraph. This is what chapters.md records (the slow
// loop and exports read prose, never fences/prompts). Empty when the text
// carries no comic fences — the caller falls back to the raw narration.
export function deriveProseFromScript(text) {
  const { panels, synopsis, isComic } = parsePanelScript(text)
  if (!isComic) return ""
  const parts = panels.map((p) => p.caption).filter(Boolean)
  if (synopsis) parts.push(synopsis)
  return parts.join("\n\n").trim()
}

// ---- Character sheet selection ---------------------------------------------
// A panel's `characters:` names are mapped to reference-sheet files through
// story/image/characters.md: the Image agent keeps one section per character
// (heading or bold-name lead) and records the literal
// story/includes/characters/... sheet path inside that section. Parsing and
// matching are pure so they are testable; the fs glue lives in
// runtime/comicPanels.js.

const SHEET_PATH_RE = /story\/includes\/characters\/[^\s)\]`"'：:，。]+/

// Loose name normalization for cross-matching a panel's name against a spec
// section's heading: lowercase, punctuation/whitespace stripped. CJK names
// match by containment in either direction (a courtesy/short form matches the
// full name).
function normalizeCharacterName(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[\s·•.,，。:：;；'"“”‘’()（）[\]【】<>《》-]+/g, "")
}

// Parse characters.md into [{ name, sheet }] where sheet is the section's
// recorded story/includes/characters/... path ("" when the section has none).
// A section starts at a markdown heading (#...) or a bold-name lead (**名**).
export function parseCharacterSheetIndex(markdown) {
  const entries = []
  let current = null
  for (const line of String(markdown || "").split(/\r?\n/)) {
    const heading = /^#{1,6}\s+(.+?)\s*$/.exec(line) || /^\*\*([^*]+)\*\*/.exec(line.trim())
    if (heading) {
      const name = heading[1].replace(/[*_`]/g, "").trim()
      // Drop generic headings (the file title etc.): a usable section name is
      // short; long sentences are prose, not names.
      current = name && name.length <= 32 ? { name, sheet: "" } : null
      if (current) entries.push(current)
      continue
    }
    if (current && !current.sheet) {
      const m = SHEET_PATH_RE.exec(line)
      if (m) current.sheet = m[0]
    }
  }
  return entries.filter((e) => e.name)
}

// Match the panel's character names against the index. Returns the matched
// sheet rels in index order, deduped, capped. Unmatched names come back too so
// the caller can surface them (a misspelled name silently anchoring nothing is
// the failure mode to avoid).
export function matchCharacterSheets(names, entries, { cap = 5 } = {}) {
  const sheets = []
  const unmatched = []
  for (const raw of Array.isArray(names) ? names : []) {
    const wanted = normalizeCharacterName(raw)
    if (!wanted) continue
    const hit = (Array.isArray(entries) ? entries : []).find((entry) => {
      const have = normalizeCharacterName(entry.name)
      return have && (have.includes(wanted) || wanted.includes(have))
    })
    if (hit?.sheet) {
      if (!sheets.includes(hit.sheet)) sheets.push(hit.sheet)
    } else {
      unmatched.push(String(raw))
    }
  }
  return { sheets: sheets.slice(0, Math.max(0, cap)), unmatched }
}

// ---- Sequential reveal (renderer gating) -----------------------------------
// A live comic turn reveals like a strip being drawn: panel K+1 stays hidden
// until panel K's image has RESOLVED (ready, or failed → caption-only), so the
// reader is never reading ahead of the artwork. Replayed turns (no live
// status) show everything at once — their images load straight from disk.
//
// `statuses` carries both keying schemes: byRel (paths exist once the runtime
// injected them at completion) and byIndex (the only stable key while the
// text is still streaming, before injection).
export function resolveComicPanelStatus(panel, statuses = {}) {
  const byRel = panel?.image ? statuses.byRel?.[panel.image] : undefined
  const byIndex = statuses.byIndex?.[panel?.index]
  // byRel wins when both exist (it is the durable key), except a byIndex
  // "ready" never downgrades to an older byRel value.
  if (byIndex === "ready" || byRel === "ready") return "ready"
  return byRel || byIndex
}

export function visibleComicPanelCount(panels, statuses = {}, { gated = false } = {}) {
  const list = Array.isArray(panels) ? panels : []
  if (!gated) return list.length
  let count = 0
  for (const panel of list) {
    count += 1
    const status = resolveComicPanelStatus(panel, statuses)
    if (status !== "ready" && status !== "failed") break
  }
  return count
}
