// Plain-text export. Tracks the openovel reading-view aesthetic: quiet
// chrome, content does the talking. We use a single thin rule, no decorative
// dingbats. UTF-8 BOM so Notepad on Windows reads it as UTF-8 by default.
//
// Layout per turn:
//
//     <CHAPTER LABEL>     ← e.g. "第 2 章" or "Prologue"
//     ────────────────
//
//     › <reader action>   (skipped for the auto-seed prologue)
//
//     <paragraph 1>
//
//     <paragraph 2>
//     ...
//
// Returns a Node Buffer.

const RULE = "─".repeat(28)
const BOM = "﻿"

const STRINGS = {
  zh: {
    chapter: (n) => `第 ${n} 章`,
    prologue: "序章",
    brand: "openovel",
    powered: "由 openovel 生成",
    exportDate: "导出日期",
    disclaimer: "内容由 AI 创作。",
    briefLabel: "原始构想",
  },
  en: {
    chapter: (n) => `Chapter ${n}`,
    prologue: "Prologue",
    brand: "openovel",
    powered: "Generated by openovel",
    exportDate: "Export date",
    disclaimer: "Content authored by AI.",
    briefLabel: "Original brief",
  },
}

export function generateTxt(data) {
  const strings = STRINGS[data.locale] || STRINGS.en
  const lines = []

  // ── Title block ──
  lines.push(data.title)
  lines.push(RULE)
  lines.push("")
  lines.push("")

  // ── Brief preface ──
  if (data.brief) {
    lines.push(strings.briefLabel)
    lines.push(RULE)
    lines.push("")
    for (const block of data.brief.split(/\n{2,}/).map((s) => s.trim()).filter(Boolean)) {
      lines.push(block)
      lines.push("")
    }
    lines.push("")
  }

  // ── Chapters ──
  for (const ch of data.chapters) {
    const heading = ch.turn === 0 ? strings.prologue : strings.chapter(ch.turn)
    lines.push(heading)
    lines.push(RULE)
    lines.push("")
    if (ch.action) {
      lines.push(`› ${ch.action}`)
      lines.push("")
    }
    for (const p of ch.paragraphs) {
      lines.push(p)
      lines.push("")
    }
    lines.push("")
  }

  // ── Colophon ──
  const date = data.exportedAt.slice(0, 10)
  lines.push(RULE)
  lines.push(strings.brand)
  lines.push(`${strings.exportDate} · ${date}`)
  lines.push(strings.disclaimer)
  lines.push("")

  return Buffer.from(BOM + lines.join("\n"), "utf8")
}
