// Thin convenience layer over `window.openovel.dispatch`. Each method here
// matches the SessionViewModel surface allow-listed in
// src/electron/transport/embedded.js. Returns a stable object so consumers
// can destructure without React re-rendering all the time.

const actions = {
  setInput: (text) => window.openovel.dispatch("setInput", text),
  appendInput: (text) => window.openovel.dispatch("appendInput", text),
  backspaceInput: () => window.openovel.dispatch("backspaceInput"),
  clearInput: () => window.openovel.dispatch("clearInput"),
  pickOption: (n) => window.openovel.dispatch("pickOption", n),
  submitOption: (n) => window.openovel.dispatch("submitOption", n),
  submit: () => window.openovel.dispatch("submit"),
  submitReaderText: () => window.openovel.dispatch("submitReaderText"),
  moveStorySelector: (delta) => window.openovel.dispatch("moveStorySelector", delta),
  setStorySearch: (query) => window.openovel.dispatch("setStorySearch", query),
  setStorySort: (sortBy) => window.openovel.dispatch("setStorySort", sortBy),
  confirmStorySelection: () => window.openovel.dispatch("confirmStorySelection"),
  confirmStoryName: (payload) => window.openovel.dispatch("confirmStoryName", payload),
  cancelStoryNaming: () => window.openovel.dispatch("cancelStoryNaming"),
  answerOnboarding: (answer) => window.openovel.dispatch("answerOnboarding", answer),
  skipOnboarding: () => window.openovel.dispatch("skipOnboarding"),
  advanceOnboardingFromApiKey: () => window.openovel.dispatch("advanceOnboardingFromApiKey"),
  goBackInOnboarding: () => window.openovel.dispatch("goBackInOnboarding"),
  appendCompose: (text) => window.openovel.dispatch("appendCompose", text),
  backspaceCompose: () => window.openovel.dispatch("backspaceCompose"),
  newlineCompose: () => window.openovel.dispatch("newlineCompose"),
  setComposeBuffer: (text) => window.openovel.dispatch("setComposeBuffer", text),
  beginPaste: () => window.openovel.dispatch("beginPaste"),
  endPaste: () => window.openovel.dispatch("endPaste"),
  cancelCompose: () => window.openovel.dispatch("cancelCompose"),
  submitCompose: () => window.openovel.dispatch("submitCompose"),
  requestExit: () => window.openovel.dispatch("requestExit"),
  readStoryFile: (rel) => window.openovel.dispatch("readStoryFile", rel),
  expandStoryTreeNode: (rel) => window.openovel.dispatch("expandStoryTreeNode", rel),
  collapseStoryTreeNode: (rel) => window.openovel.dispatch("collapseStoryTreeNode", rel),
  switchToStory: (id) => window.openovel.dispatch("switchToStory", id),
  deleteStory: (id) => window.openovel.dispatch("deleteStory", id),
  renameStory: (id, name) => window.openovel.dispatch("renameStory", id, name),
  setStoryMode: (id, mode) => window.openovel.dispatch("setStoryMode", id, mode),
  restartStory: (id) => window.openovel.dispatch("restartStory", id),
  listStoryVersions: (id) => window.openovel.dispatch("listStoryVersions", id),
  restoreStoryVersion: (id, versionId) => window.openovel.dispatch("restoreStoryVersion", id, versionId),
  deleteStoryVersion: (id, versionId) => window.openovel.dispatch("deleteStoryVersion", id, versionId),
  replayStoryInit: (id) => window.openovel.dispatch("replayStoryInit", id),
  resumeStoryInit: (id) => window.openovel.dispatch("resumeStoryInit", id),
  setReplaySpeed: (mult) => window.openovel.dispatch("setReplaySpeed", mult),
  goToLibrary: () => window.openovel.dispatch("goToLibrary"),
  setInitInput: (text) => window.openovel.dispatch("setInitInput", text),
  submitInitIntent: () => window.openovel.dispatch("submitInitIntent"),
  submitInitFeedback: (text) => window.openovel.dispatch("submitInitFeedback", text),
  continueInitWithDepth: (depth) => window.openovel.dispatch("continueInitWithDepth", depth),
  submitInitAskUserAnswer: (text) => window.openovel.dispatch("submitInitAskUserAnswer", text),
  confirmInitDone: () => window.openovel.dispatch("confirmInitDone"),
  cancelInitChat: () => window.openovel.dispatch("cancelInitChat"),
  listPermissions: (opts) => window.openovel.dispatch("listPermissions", opts || {}),
  approvePermission: (id) => window.openovel.dispatch("approvePermission", id),
  denyPermission: (id, reason) => window.openovel.dispatch("denyPermission", id, reason || ""),
  listTransactions: (opts) => window.openovel.dispatch("listTransactions", opts || {}),
  rollbackTransaction: (txId) => window.openovel.dispatch("rollbackTransaction", txId),
}

export function useVmActions() {
  return actions
}
